/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ReverseStringService_H
#define ReverseStringService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "reverseString_types.h"

namespace thrift {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ReverseStringServiceIf {
 public:
  virtual ~ReverseStringServiceIf() {}
  virtual void reverseString(std::string& _return, const std::string& stringToReverse) = 0;
};

class ReverseStringServiceIfFactory {
 public:
  typedef ReverseStringServiceIf Handler;

  virtual ~ReverseStringServiceIfFactory() {}

  virtual ReverseStringServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ReverseStringServiceIf* /* handler */) = 0;
};

class ReverseStringServiceIfSingletonFactory : virtual public ReverseStringServiceIfFactory {
 public:
  ReverseStringServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<ReverseStringServiceIf>& iface) : iface_(iface) {}
  virtual ~ReverseStringServiceIfSingletonFactory() {}

  virtual ReverseStringServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ReverseStringServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<ReverseStringServiceIf> iface_;
};

class ReverseStringServiceNull : virtual public ReverseStringServiceIf {
 public:
  virtual ~ReverseStringServiceNull() {}
  void reverseString(std::string& /* _return */, const std::string& /* stringToReverse */) {
    return;
  }
};

typedef struct _ReverseStringService_reverseString_args__isset {
  _ReverseStringService_reverseString_args__isset() : stringToReverse(false) {}
  bool stringToReverse :1;
} _ReverseStringService_reverseString_args__isset;

class ReverseStringService_reverseString_args {
 public:

  ReverseStringService_reverseString_args(const ReverseStringService_reverseString_args&);
  ReverseStringService_reverseString_args& operator=(const ReverseStringService_reverseString_args&);
  ReverseStringService_reverseString_args() : stringToReverse() {
  }

  virtual ~ReverseStringService_reverseString_args() throw();
  std::string stringToReverse;

  _ReverseStringService_reverseString_args__isset __isset;

  void __set_stringToReverse(const std::string& val);

  bool operator == (const ReverseStringService_reverseString_args & rhs) const
  {
    if (!(stringToReverse == rhs.stringToReverse))
      return false;
    return true;
  }
  bool operator != (const ReverseStringService_reverseString_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ReverseStringService_reverseString_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ReverseStringService_reverseString_pargs {
 public:


  virtual ~ReverseStringService_reverseString_pargs() throw();
  const std::string* stringToReverse;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ReverseStringService_reverseString_result__isset {
  _ReverseStringService_reverseString_result__isset() : success(false) {}
  bool success :1;
} _ReverseStringService_reverseString_result__isset;

class ReverseStringService_reverseString_result {
 public:

  ReverseStringService_reverseString_result(const ReverseStringService_reverseString_result&);
  ReverseStringService_reverseString_result& operator=(const ReverseStringService_reverseString_result&);
  ReverseStringService_reverseString_result() : success() {
  }

  virtual ~ReverseStringService_reverseString_result() throw();
  std::string success;

  _ReverseStringService_reverseString_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const ReverseStringService_reverseString_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ReverseStringService_reverseString_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ReverseStringService_reverseString_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ReverseStringService_reverseString_presult__isset {
  _ReverseStringService_reverseString_presult__isset() : success(false) {}
  bool success :1;
} _ReverseStringService_reverseString_presult__isset;

class ReverseStringService_reverseString_presult {
 public:


  virtual ~ReverseStringService_reverseString_presult() throw();
  std::string* success;

  _ReverseStringService_reverseString_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ReverseStringServiceClient : virtual public ReverseStringServiceIf {
 public:
  ReverseStringServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ReverseStringServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void reverseString(std::string& _return, const std::string& stringToReverse);
  void send_reverseString(const std::string& stringToReverse);
  void recv_reverseString(std::string& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ReverseStringServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<ReverseStringServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ReverseStringServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_reverseString(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ReverseStringServiceProcessor(::apache::thrift::stdcxx::shared_ptr<ReverseStringServiceIf> iface) :
    iface_(iface) {
    processMap_["reverseString"] = &ReverseStringServiceProcessor::process_reverseString;
  }

  virtual ~ReverseStringServiceProcessor() {}
};

class ReverseStringServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ReverseStringServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< ReverseStringServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< ReverseStringServiceIfFactory > handlerFactory_;
};

class ReverseStringServiceMultiface : virtual public ReverseStringServiceIf {
 public:
  ReverseStringServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<ReverseStringServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ReverseStringServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<ReverseStringServiceIf> > ifaces_;
  ReverseStringServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<ReverseStringServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void reverseString(std::string& _return, const std::string& stringToReverse) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->reverseString(_return, stringToReverse);
    }
    ifaces_[i]->reverseString(_return, stringToReverse);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ReverseStringServiceConcurrentClient : virtual public ReverseStringServiceIf {
 public:
  ReverseStringServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ReverseStringServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void reverseString(std::string& _return, const std::string& stringToReverse);
  int32_t send_reverseString(const std::string& stringToReverse);
  void recv_reverseString(std::string& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
