/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef reverseString_CONSTANTS_H
#define reverseString_CONSTANTS_H

#include "reverseString_types.h"

namespace thrift {

class reverseStringConstants {
 public:
  reverseStringConstants();

};

extern const reverseStringConstants g_reverseString_constants;

} // namespace

#endif
