/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "reverseString_constants.h"

namespace thrift {

const reverseStringConstants g_reverseString_constants;

reverseStringConstants::reverseStringConstants() {
}

} // namespace

